customCommands:
  - key: "<c-s>"
    command: 'tmux neww ''zsh -i -c "git-worktree-switch {{.SelectedLocalBranch.Name}}"'''
    context: "localBranches"
    loadingText: "Switch worktree"
  - key: "<c-c>"
    command: "tmux neww 'zsh -i -c git-worktree-create'"
    context: "localBranches"
    loadingText: "Create worktree from existing branch"
  - key: "<c-n>"
    prompts:
      - type: "input"
        title: "GitHub Issue/Branch name:"
        initialValue: ""
        key: "WorktreeToCreate"
    command: 'tmux neww ''zsh -i -c "git-worktree-create {{.Form.WorktreeToCreate}}"'''
    context: "localBranches"
    loadingText: "Create new branch+worktree"
  - key: "<c-d>"
    command: 'tmux neww ''zsh -i -c "git-worktree-delete {{.SelectedLocalBranch.Name}}"'''
    context: "localBranches"
    loadingText: "Delete selected branch+worktree"
